#pragma once

#include <functional>

#include <memory>

#include "envoy/common/pure.h"
#include "envoy/stats/store.h"

#include "nighthawk/client/benchmark_client.h"
#include "nighthawk/common/phase.h"
#include "nighthawk/common/statistic.h"
#include "nighthawk/common/worker.h"

namespace Nighthawk {
namespace Client {

/**
 * What a snapshot of a run in flight carries for each statistic.
 */
enum class SnapshotDetail {
  // Count, mean, pstdev, min and max, read from the live statistic. No percentiles, and no
  // histogram is allocated: a snapshot costs a few hundred bytes per statistic.
  Summary,
  // A copy of the statistic, percentiles included. For a histogram-backed statistic that is a
  // histogram's worth of memory per copy -- megabytes -- allocated on the worker's thread.
  Full,
};

/**
 * Interface for a threaded benchmark client worker.
 */
class ClientWorker : virtual public Worker {
public:
  /**
   * Gets the statistics, keyed by id.
   * @return StatisticPtrMap A map of Statistics keyed by id.
   */
  virtual StatisticPtrMap statistics() const PURE;

  /**
   * @return const std::map<std::string, uint64_t>& The worker-specific counter values.
   * Gets filled when the worker has completed its task, empty before that.
   */
  virtual const std::map<std::string, uint64_t>& threadLocalCounterValues() PURE;

  /**
   * @return const Phase& associated to this worker.
   */
  virtual const Phase& phase() const PURE;

  /**
   * Requests execution cancellation.
   */
  virtual void requestExecutionCancellation() PURE;

  /**
   * Posts a job to the worker's own thread that snapshots its statistics and hands the result
   * to callback, there. The job never runs if the worker's dispatcher has already exited, so a
   * caller waits for the callback with a bound, and must keep whatever the callback touches
   * alive until it has run or can no longer run.
   *
   * @param detail summaries of the statistics, or full copies of them.
   * @param still_wanted asked on the worker's thread before anything is copied. When it
   * says no -- the caller stopped waiting -- nothing is built and the callback is not called:
   * a job that runs late must not allocate copies nobody will take, least of all Full ones.
   * @param callback receives one Statistic per statistic of the worker, on the worker's thread.
   */
  virtual void snapshotStatistics(SnapshotDetail detail, std::function<bool()> still_wanted,
                                  std::function<void(std::vector<StatisticPtr>)> callback) PURE;

  /**
   * Get additional output generated by UserDefinedOutput plugins associated with this client
   * worker.
   *
   * @return a vector of protos, each the output result to a User Defined Output Plugin.
   */
  virtual std::vector<nighthawk::client::UserDefinedOutput>
  getUserDefinedOutputResults() const PURE;
};

using ClientWorkerPtr = std::unique_ptr<ClientWorker>;

} // namespace Client
} // namespace Nighthawk
