#pragma once

#include <functional>

#include <memory>

#include "envoy/common/pure.h"
#include "envoy/stats/store.h"

#include "nighthawk/client/benchmark_client.h"
#include "nighthawk/common/phase.h"
#include "nighthawk/common/statistic.h"
#include "nighthawk/common/worker.h"

namespace Nighthawk {
namespace Client {

/**
 * Interface for a threaded benchmark client worker.
 */
class ClientWorker : virtual public Worker {
public:
  /**
   * Gets the statistics, keyed by id.
   * @return StatisticPtrMap A map of Statistics keyed by id.
   */
  virtual StatisticPtrMap statistics() const PURE;

  /**
   * @return const std::map<std::string, uint64_t>& The worker-specific counter values.
   * Gets filled when the worker has completed its task, empty before that.
   */
  virtual const std::map<std::string, uint64_t>& threadLocalCounterValues() PURE;

  /**
   * @return const Phase& associated to this worker.
   */
  virtual const Phase& phase() const PURE;

  /**
   * Requests execution cancellation.
   */
  virtual void requestExecutionCancellation() PURE;

  /**
   * Posts a job to the worker's own thread that copies its statistics and hands the copies to
   * callback, there. The job never runs if the worker's dispatcher has already exited, so a
   * caller waits for the callback with a bound, and must keep whatever the callback touches
   * alive until it has run or can no longer run.
   *
   * @param callback receives the copies, on the worker's thread.
   */
  virtual void snapshotStatistics(std::function<void(std::vector<StatisticPtr>)> callback) PURE;

  /**
   * Get additional output generated by UserDefinedOutput plugins associated with this client
   * worker.
   *
   * @return a vector of protos, each the output result to a User Defined Output Plugin.
   */
  virtual std::vector<nighthawk::client::UserDefinedOutput>
  getUserDefinedOutputResults() const PURE;
};

using ClientWorkerPtr = std::unique_ptr<ClientWorker>;

} // namespace Client
} // namespace Nighthawk
