load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "report",
    srcs = ["report.go"],
    importpath = "github.com/bpalermo/sortie/internal/report",
    visibility = ["//:__subpackages__"],
    deps = [
        "//engine/api/client:base_go_proto",
        "//internal/compile",
        "//internal/metric",
        "//internal/nh",
        "//internal/run",
    ],
)

go_test(
    name = "report_test",
    size = "small",
    srcs = [
        "report_test.go",
        "summary_internal_test.go",
    ],
    embed = [":report"],
    deps = [
        "//engine/api/client:base_go_proto",
        "//internal/compile",
        "//internal/nh",
        "//internal/result",
        "//internal/run",
        "//internal/threshold",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
