load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "result",
    srcs = ["result.go"],
    importpath = "github.com/bpalermo/sortie/internal/result",
    visibility = ["//:__subpackages__"],
    deps = [
        "//gen/api/client",
        "//internal/metric",
        "//internal/threshold",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)

go_test(
    name = "result_test",
    size = "small",
    srcs = ["result_test.go"],
    embed = [":result"],
    deps = [
        "//gen/api/client",
        "//internal/threshold",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)
