load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cli",
    srcs = [
        "compile.go",
        "root.go",
        "run.go",
        "validate.go",
    ],
    importpath = "github.com/bpalermo/sortie/internal/cli",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/compile",
        "//internal/plan",
        "//internal/report",
        "//internal/run",
        "@com_github_spf13_cobra//:cobra",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_test(
    name = "cli_test",
    srcs = ["cli_test.go"],
    embed = [":cli"],
    deps = [
        "@nighthawk_api//:client_go_proto",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)
