load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "sortie_lib",
    srcs = ["main.go"],
    importpath = "github.com/bpalermo/sortie/cmd/sortie",
    visibility = ["//visibility:private"],
    deps = [
        "//internal/compile",
        "//internal/plan",
        "//internal/report",
        "//internal/run",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_binary(
    name = "sortie",
    embed = [":sortie_lib"],
    visibility = ["//visibility:public"],
)
