load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "compile",
    srcs = [
        "clone.go",
        "compile.go",
    ],
    importpath = "github.com/bpalermo/sortie/internal/compile",
    visibility = ["//:__subpackages__"],
    deps = [
        "//engine/api/client:base_go_proto",
        "//engine/api/rate_limiter:rate_limiter_plugin_go_proto",
        "//internal/plan",
        "@envoy_api//envoy/config/core/v3:pkg_go_proto",
        "@envoy_api//envoy/extensions/transport_sockets/tls/v3:pkg_go_proto",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/wrapperspb",
    ],
)

go_test(
    name = "compile_test",
    size = "small",
    srcs = ["compile_test.go"],
    embed = [":compile"],
    deps = [
        "//engine/api/client:base_go_proto",
        "//engine/api/rate_limiter:rate_limiter_plugin_go_proto",
        "//internal/plan",
        "@envoy_api//envoy/config/core/v3:pkg_go_proto",
        "@envoy_api//envoy/extensions/transport_sockets/tls/v3:pkg_go_proto",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/anypb",
        "@org_golang_google_protobuf//types/known/durationpb",
        "@org_golang_google_protobuf//types/known/wrapperspb",
    ],
)
