load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "run",
    srcs = ["run.go"],
    importpath = "github.com/bpalermo/sortie/internal/run",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/compile",
        "//internal/nh",
        "//internal/plan",
        "//internal/result",
        "//internal/threshold",
        "@nighthawk_api//:client_go_proto",
        "@org_golang_x_sync//errgroup",
    ],
)
