load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "run",
    srcs = ["run.go"],
    importpath = "github.com/bpalermo/sortie/internal/run",
    visibility = ["//:__subpackages__"],
    deps = [
        "//engine/api/client:base_go_proto",
        "//internal/compile",
        "//internal/nh",
        "//internal/plan",
        "//internal/result",
        "//internal/threshold",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_protobuf//proto",
    ],
)

go_test(
    name = "run_test",
    size = "small",
    srcs = [
        "fake_service_test.go",
        "run_test.go",
    ],
    deps = [
        ":run",
        "//engine/api/client:base_go_proto",
        "//internal/plan",
        "@org_golang_google_genproto_googleapis_rpc//status",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)
