"""Lint aspects for the Starlark in this repository.

aspect_rules_lint ships no Go linter, so Go is covered by rules_go's nogo
(see //tools/nogo) and this file covers the build files.

Only hand-written Starlark is linted. The BUILD files under internal/ and cmd/
are generated by Gazelle, which already emits canonical formatting, and CI
separately fails if regenerating them produces a diff.
"""

load("@aspect_rules_lint//lint:buildifier.bzl", "lint_buildifier_aspect")
load("@aspect_rules_lint//lint:lint_test.bzl", "lint_test")

# @buildifier_prebuilt//:buildifier is a toolchain-resolved launcher script
# whose own runfiles never make it into this aspect's sandboxed actions (see
# the MODULE.bazel comment next to buildifier_linux_amd64 for why), so this
# points straight at the downloaded linux/amd64 binary instead - a
# self-contained executable that needs no runfiles to run.
#
# buildifier's own -mode defaults to "fix", i.e. rewrite the file in place,
# and aspect_rules_lint's plain (non--fix) lint action never overrides that.
# The srcs it lints are symlinks through the sandbox into the real checkout,
# so a silent "fix" would mutate this repo's source files as a side effect
# of running a *_test, and here the checkout and Bazel's output_user_root
# sit on different filesystems, so the rewrite's rename() crashes with
# "invalid cross-device link" instead. -mode=check makes buildifier only
# report; nothing is ever written back.
buildifier = lint_buildifier_aspect(
    binary = Label("//tools/lint:buildifier"),
    args = ["--mode=check"],
)

buildifier_test = lint_test(aspect = buildifier)
