load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "nh",
    srcs = [
        "client.go",
        "distributor.go",
    ],
    importpath = "github.com/bpalermo/sortie/internal/nh",
    visibility = ["//:__subpackages__"],
    deps = [
        "@envoy_api//envoy/config/core/v3:pkg_go_proto",
        "@nighthawk_api//:client_go_proto",
        "@nighthawk_api//:distributor_go_proto",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)
