load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "nh",
    srcs = [
        "client.go",
        "distributor.go",
    ],
    importpath = "github.com/bpalermo/sortie/internal/nh",
    visibility = ["//:__subpackages__"],
    deps = [
        "@envoy_api//envoy/config/core/v3:pkg_go_proto",
        "@nighthawk_api//:client_go_proto",
        "@nighthawk_api//:distributor_go_proto",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)

go_test(
    name = "nh_test",
    srcs = ["distributor_test.go"],
    deps = [
        ":nh",
        "@envoy_api//envoy/config/core/v3:pkg_go_proto",
        "@nighthawk_api//:client_go_proto",
        "@nighthawk_api//:distributor_go_proto",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)
