load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "chartconfig_lib",
    srcs = [
        "chartconfig.go",
        "main.go",
    ],
    importpath = "github.com/bpalermo/sortie/bazel/chartconfig",
    visibility = ["//visibility:private"],
    deps = ["@io_k8s_sigs_yaml//:yaml"],
)

go_binary(
    name = "chartconfig",
    embed = [":chartconfig_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "chartconfig_test",
    size = "small",
    srcs = ["chartconfig_test.go"],
    embed = [":chartconfig_lib"],
)
