load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "threshold",
    srcs = ["threshold.go"],
    importpath = "github.com/bpalermo/sortie/internal/threshold",
    visibility = ["//:__subpackages__"],
    deps = [
        "//gen/api/client",
        "//internal/metric",
    ],
)

go_test(
    name = "threshold_test",
    size = "small",
    srcs = ["threshold_test.go"],
    embed = [":threshold"],
    deps = [
        "//gen/api/client",
        "//internal/metric",
        "@org_golang_google_protobuf//types/known/durationpb",
    ],
)
