"""chart_push: publishes a packaged chart to a repository it NAMES, with oras.

`helm push` derives the repository's last path segment from Chart.yaml's
`name:` and nothing else, so it can only publish chart `sortie` as
`<base>/sortie` -- the driver image's repository on a flat registry. Quay has
no nested repositories, and the chart lives under the `chart-` prefix
(//bazel:registry.bzl). So this writes exactly the artifact `helm push`
writes -- the packaged .tgz as an
`application/vnd.cncf.helm.chart.content.v1.tar+gzip` layer and Chart.yaml (as
JSON, //bazel/chartconfig) as the `application/vnd.cncf.helm.config.v1+json`
config -- with `oras push <repository>:<chart version>`, and
`helm pull oci://<repository> --version <chart version>` reads it back like any
helm-pushed chart.
"""

load("@rules_helm//helm:defs.bzl", "HelmPackageInfo")

_PUSHER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl chart_push. Do not edit.
#
# Pushes ONE packaged chart to @@REPOSITORY@@:<chart version> as the same OCI
# artifact `helm push` writes, with oras (see chart_push's doc for why).
# --- begin runfiles.bash initialization v3 ---
# shellcheck disable=SC1090
set -uo pipefail
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
	source "$0.runfiles/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	{
		echo >&2 "ERROR: cannot find $f"
		exit 1
	}
f=
set -e
# --- end runfiles.bash initialization v3 ---

die() {
	echo "chart_push @@LABEL@@: $*" >&2
	exit 1
}

# Validation seams, never set by the publish workflow: CHART_PUSH_REPOSITORY
# pushes somewhere else (a local registry, to prove `helm pull` reads the
# result). Extra arguments go to `oras push` (e.g. --plain-http for that local
# registry).
oras="$(rlocation '@@ORAS@@')"
chart="$(rlocation '@@CHART@@')"
config="$(rlocation '@@CONFIG@@')"
meta="$(rlocation '@@META@@')"
repository="${CHART_PUSH_REPOSITORY:-@@REPOSITORY@@}"
for f in "$oras" "$chart" "$config" "$meta"; do
	{ [ -n "$f" ] && [ -r "$f" ]; } || die "missing runfile '${f}'"
done
read -r name version <"$meta" || die "unreadable chart metadata ${meta}"
[ "$name" = '@@NAME@@' ] || die "the package is chart '${name}', but this target pushes chart '@@NAME@@' to ${repository}"
# helm's own rule: an OCI tag cannot hold '+', so SemVer build metadata is
# written with '_' (helm push and helm pull both translate it).
tag="${version//+/_}"
if ! [[ "$tag" =~ ^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$ ]]; then
	die "version '${version}' is not a valid OCI tag -- an unstamped package? Publish with --stamp."
fi
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# The layer is named the way `helm package` names the archive; oras records the
# file name as the layer's title annotation and wants a relative path.
cp "$chart" "${work}/${name}-${version}.tgz"
cp "$config" "${work}/config.json"
cd "$work"
echo "pushing ${name} ${version} -> ${repository}:${tag}"
"$oras" push "$@" \\
	--annotation "org.opencontainers.image.title=${name}" \\
	--annotation "org.opencontainers.image.version=${version}" \\
	--config "config.json:application/vnd.cncf.helm.config.v1+json" \\
	"${repository}:${tag}" \\
	"${name}-${version}.tgz:application/vnd.cncf.helm.chart.content.v1.tar+gzip"
echo "pushed ${repository}:${tag} (helm pull oci://${repository} --version ${version})"
"""

def _rlocationpath(ctx, f):
    path = f.short_path
    if path.startswith("../"):
        return path[3:]
    return ctx.workspace_name + "/" + path

def _chart_push_impl(ctx):
    pkg = ctx.attr.package[HelmPackageInfo]
    oras = ctx.executable._oras
    config = ctx.actions.declare_file(ctx.label.name + ".config.json")
    meta = ctx.actions.declare_file(ctx.label.name + ".meta")
    ctx.actions.run(
        executable = ctx.executable._chartconfig,
        arguments = [
            "-chart",
            pkg.chart.path,
            "-config_out",
            config.path,
            "-meta_out",
            meta.path,
        ],
        inputs = [pkg.chart],
        outputs = [config, meta],
        mnemonic = "HelmChartConfig",
        progress_message = "Deriving the helm OCI config of %{label}",
    )
    script = _PUSHER
    for placeholder, value in [
        ("@@LABEL@@", str(ctx.label)),
        ("@@ORAS@@", _rlocationpath(ctx, oras)),
        ("@@CHART@@", _rlocationpath(ctx, pkg.chart)),
        ("@@CONFIG@@", _rlocationpath(ctx, config)),
        ("@@META@@", _rlocationpath(ctx, meta)),
        ("@@REPOSITORY@@", ctx.attr.repository),
        ("@@NAME@@", ctx.attr.chart_name),
    ]:
        script = script.replace(placeholder, value)
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)
    runfiles = ctx.runfiles(files = [oras, pkg.chart, config, meta])
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    return [DefaultInfo(
        executable = runner,
        files = depset([runner, config, meta]),
        runfiles = runfiles,
    )]

chart_push = rule(
    doc = """Pushes a packaged chart to the repository it names, with oras.

The tag is the PACKAGED version (the stamped one: `X.Y.Z-<full sha>` for a
`-{STABLE_GIT_COMMIT}` chart). A version that is not a valid OCI tag (an
unstamped build) is refused at run time, never pushed. Registry credentials come
from the Docker config, which `docker login` / docker/login-action writes.

`bazel run --stamp <target> [-- <extra oras push flags>]`.
""",
    implementation = _chart_push_impl,
    executable = True,
    attrs = {
        "chart_name": attr.string(
            doc = "The chart's Chart.yaml `name:`; the push refuses a package that is some other chart.",
            mandatory = True,
        ),
        "package": attr.label(
            doc = "The `helm_chart` target to push.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "repository": attr.string(
            doc = "Host-qualified repository, no scheme and no tag: chart_registry_url(<chart>).",
            mandatory = True,
        ),
        "_chartconfig": attr.label(
            default = Label("//bazel/chartconfig"),
            executable = True,
            cfg = "exec",
        ),
        "_oras": attr.label(
            default = Label("//bazel/oras:oras_bin"),
            executable = True,
            allow_single_file = True,
            cfg = "target",
        ),
        "_runfiles_lib": attr.label(
            default = Label("@bazel_tools//tools/bash/runfiles"),
        ),
    },
)
